{% set version = "1.16" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sparql
  version: {{ version|replace("-", "_") }}

source:
  fn: SPARQL_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/SPARQL_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SPARQL/SPARQL_{{ version }}.tar.gz
  sha256: 2cb366b2b93804c12f17254a1c37687887fc12047b58b13aab0d7a6f000e533d

# r-rcurl isn't available on Windows yet
build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 1003
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-rcurl
    - r-xml

  run:
    - r-base
    - r-rcurl
    - r-xml

test:
  commands:
    - $R -e "library('SPARQL')"  # [not win]
    - "\"%R%\" -e \"library('SPARQL')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=SPARQL
  license: GPL-3.0-only
  summary: 'Use SPARQL to pose SELECT or UPDATE queries to an end-point. '

  license_family: GPL3

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
